services:
    vscode:
        build: 
          context: $ODOO_IMAGES/vscode
          args:
            OWNER_UID: $OWNER_UID
        cap_add:
          # required by vscode
          - SYS_ADMIN
        shm_size: 4gb
        restart: "unless-stopped"
        privileged: true
        profiles:
          - manual
        # ports:
        #     - "5900:5900"
        volumes:
          - ${CUSTOMS_DIR}:/opt/src
          - ${CUSTOMS_DIR}:${CUSTOMS_DIR}
          - ${ODOO_IMAGES}/vscode/user_data:/home/userdata
          - ${ODOO_IMAGES}/vscode/entrypoint.sh:/entrypoint.sh
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker:/var/lib/docker
          - "${ODOO_IMAGES}:/home/user1/.odoo/images"
          - "${HOST_RUN_DIR}:/home/user1/.odoo/run/$PROJECT_NAME"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DISPLAY_WIDTH=${VSCODE_WIDTH}
            - DISPLAY_HEIGHT=${VSCODE_HEIGHT}
            - DISPLAY_COLOR=${VSCODE_COLOR}
    novnc_vscode:
        build:
          context: $ODOO_IMAGES/novnc
          args:
            relpathname: vscode
        restart: "unless-stopped"
        profiles:
          - manual
        links:
            - vscode
        volumes:
          - ${ODOO_IMAGES}/novnc/websockify:/root/websockify
          - ${ODOO_IMAGES}/vscode/tokens:/root/tokens
        environment:
          - DISPLAY_WIDTH=${VSCODE_WIDTH}
          - DISPLAY_HEIGHT=${VSCODE_HEIGHT}
          - DISPLAY_COLOR=${VSCODE_COLOR}
          - AUTOCONNECT=true
          # - RUN_XTERM={yes|no} (yes)
          - RUN_FLUXBOX=yes
          - VNC_SERVER=vscode:5900
          - VIEW_ONLY=false
          - TOKEN_FILE=/root/tokens
